FROM yytest_sentence_bench:v1

WORKDIR /app

# 暴露端口
EXPOSE 35000

# 启动命令 (使用 gevent worker)
#CMD ["gunicorn", \
#    "--bind", "0.0.0.0:35000", \
#    "--workers", "1", \
#    "--timeout", "300", \
#    "main:app"]
