# Namespace
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: incloud-dify  

#---
# Service
apiVersion: v1
kind: Service
metadata:
  name: incloud-text-model
  namespace: incloud-dify
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: svc-port
    nodePort: 35000
    port: 35000
    protocol: TCP
    targetPort: 35000
  selector:
    app.kubernetes.io/name: reranker
  sessionAffinity: None
  type: NodePort

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: reranker
  namespace: incloud-dify
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: reranker
  strategy:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reranker
    spec:
      containers:
      - env:
        - name: logger.level
          value: Info
        image: cr.incloudos.com:30012/library/incloud_sentence_transformer:v1
        imagePullPolicy: IfNotPresent
        name: reranker
        volumeMounts:
        - mountPath: /app/
          name: app-data
        ports:
        - containerPort: 35000
          name: svc-port
          protocol: TCP
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 64
            memory: 16Gi
          requests:
            cpu: 10m
            memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Equal
      volumes:
      - hostPath:
          path: /data/model/
          type: DirectoryOrCreate
        name: app-data



